# This is a development compose file needed only for the database.
# Run the project using `pnpm run dev` and then run this command if you need to start the databases manually.
# `pnpm run docker:start` to run the databases
# `pnpm run docker:stop` to stop the databases

services:
  postgresql:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=conar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-server
    image: redis/redis-stack:7.2.0-v19
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS="--requirepass root"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [CMD, redis-cli, -a, root, ping]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis-data:
