services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=conar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:7.2.0-v19
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS="--requirepass root"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [CMD, redis-cli, -a, root, ping]
      interval: 10s
      timeout: 5s
      retries: 5

  infisical-db:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infisical
    volumes:
      - infisical_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - infisical
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5

  infisical-redis:
    image: redis/redis-stack:7.2.0-v19
    restart: unless-stopped
    volumes:
      - infisical_redis_data:/data
    networks:
      - infisical

  infisical:
    image: infisical/infisical:latest
    restart: unless-stopped
    depends_on:
      infisical-db:
        condition: service_healthy
      infisical-redis:
        condition: service_started
    ports:
      - '8082:8080'
    environment:
      - NODE_ENV=production
      - ENCRYPTION_KEY=devfe4e407b8cfb185b406438a42a777
      - AUTH_SECRET=devERxgNsBMhQkMpMdn6MknRbjRsSvCx
      - DB_CONNECTION_URI=postgres://postgres:postgres@infisical-db:5432/infisical
      - REDIS_URL=redis://infisical-redis:6379
      - SITE_URL=http://localhost:8082
    networks:
      - infisical

volumes:
  postgres_data:
  redis_data:
  infisical_postgres_data:
  infisical_redis_data:

networks:
  infisical:
