import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: [
    'import',
    'typescript',
    'react',
    'unicorn',
    'jsdoc',
    'node',
    'promise',
    'jsx-a11y',
    'oxc',
    'vitest',
  ],
  jsPlugins: ['eslint-plugin-better-tailwindcss'],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    perf: 'warn',
  },
  env: {
    builtin: true,
    es2026: true,
    browser: true,
    node: true,
  },
  globals: {
    AudioPlaybackStats: 'readonly',
    CSSFontFaceDescriptors: 'readonly',
    CSSPseudoElement: 'readonly',
    LanguageModel: 'readonly',
    ModelContext: 'readonly',
    Sanitizer: 'readonly',
    TimelineTrigger: 'readonly',
    TimelineTriggerRange: 'readonly',
    TimelineTriggerRangeList: 'readonly',
    WebMCPEvent: 'readonly',
    XRCompositionLayer: 'readonly',
    XRCubeLayer: 'readonly',
    XRCylinderLayer: 'readonly',
    XREquirectLayer: 'readonly',
    XRLayerEvent: 'readonly',
    XRPlane: 'readonly',
    XRPlaneSet: 'readonly',
    XRProjectionLayer: 'readonly',
    XRQuadLayer: 'readonly',
    XRSubImage: 'readonly',
    XRWebGLSubImage: 'readonly',
  },
  settings: {
    'better-tailwindcss': {
      entryPoint: './packages/ui/src/styles/globals.css',
    },
  },
  ignorePatterns: [
    '**/.DS_Store',
    '**/node_modules',
    '**/.turbo',
    '**/*.tsbuildinfo',
    '**/.idea',
    '**/.node-modules-inspector',
    '**/.pnpm-store',
    '**/dist',
    '**/package-lock.json',
    '**/yarn.lock',
    '**/pnpm-lock.yaml',
    '**/bun.lockb',
    '**/output',
    '**/coverage',
    '**/temp',
    '**/.temp',
    '**/tmp',
    '**/.tmp',
    '**/.history',
    '**/.vitepress/cache',
    '**/.nuxt',
    '**/.next',
    '**/.svelte-kit',
    '**/.vercel',
    '**/.changeset',
    '**/.cache',
    '**/.output',
    '**/.vite-inspect',
    '**/.yarn',
    '**/CHANGELOG*.md',
    '**/LICENSE*',
    '**/*.min.*',
    '**/__snapshots__',
    '**/vite.config.*.timestamp-*',
    '**/auto-import?(s).d.ts',
    '**/components.d.ts',
    '**/.context',
    '**/.claude',
    '**/.agents',
    '**/.*/skills',
    '**/*.md',
    '**/routeTree.gen.ts',
    '**/release/**/*',
    '**/.tanstack/**/*',
    '**/.nitro/**/*',
    '**/.output/**/*',
    '**/.source/**/*',
    '**/dist-electron/**/*',
    '**/dist-desktop/**/*',
    '**/playwright-report/**/*',
    '**/test-results/**/*',
    '**/.types/**/*',
    '**/migrations/**/*',
    '**/migrations.json',
  ],
  rules: {
    'accessor-pairs': [
      'error',
      {
        enforceForClassMembers: true,
        setWithoutGet: true,
      },
    ],
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'constructor-super': 'error',
    'default-case-last': 'error',
    eqeqeq: ['error', 'smart'],
    'new-cap': [
      'error',
      {
        capIsNew: false,
        newIsCap: true,
        properties: true,
      },
    ],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-async-promise-executor': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-console': [
      'warn',
      {
        allow: ['warn', 'error'],
      },
    ],
    'no-const-assign': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': [
      'error',
      {
        allowEmptyCatch: true,
      },
    ],
    'no-empty-pattern': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-implied-eval': 'error',
    'no-import-assign': 'error',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'error',
    'no-labels': [
      'error',
      {
        allowLoop: false,
        allowSwitch: false,
      },
    ],
    'no-lone-blocks': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': [
      'error',
      {
        builtinGlobals: false,
      },
    ],
    'no-regex-spaces': 'error',
    'no-restricted-globals': [
      'error',
      {
        message: 'Use `globalThis` instead.',
        name: 'global',
      },
      {
        message: 'Use `globalThis` instead.',
        name: 'self',
      },
    ],
    'no-restricted-properties': [
      'error',
      {
        message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.',
        property: '__proto__',
      },
      {
        message: 'Use `Object.defineProperty` instead.',
        property: '__defineGetter__',
      },
      {
        message: 'Use `Object.defineProperty` instead.',
        property: '__defineSetter__',
      },
      {
        message: 'Use `Object.getOwnPropertyDescriptor` instead.',
        property: '__lookupGetter__',
      },
      {
        message: 'Use `Object.getOwnPropertyDescriptor` instead.',
        property: '__lookupSetter__',
      },
    ],
    'no-self-assign': [
      'error',
      {
        props: true,
      },
    ],
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow': 'off',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-underscore-dangle': [
      'warn',
      {
        allow: ['__filename', '__dirname', '_url', '_URL'],
      },
    ],
    'no-unexpected-multiline': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': [
      'error',
      {
        defaultAssignment: false,
      },
    ],
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
        allowTernary: true,
      },
    ],
    'no-unused-vars': [
      'error',
      {
        args: 'none',
        argsIgnorePattern: '^_',
        caughtErrors: 'none',
        ignoreRestSiblings: true,
        vars: 'all',
        varsIgnorePattern: '^_',
      },
    ],
    'no-use-before-define': [
      'error',
      {
        classes: false,
        functions: false,
        variables: true,
      },
    ],
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-with': 'error',
    'object-shorthand': [
      'error',
      'always',
      {
        avoidQuotes: true,
        ignoreConstructors: false,
      },
    ],
    'prefer-const': [
      'error',
      {
        destructuring: 'all',
        ignoreReadBeforeAssign: true,
      },
    ],
    'prefer-exponentiation-operator': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': [
      'error',
      {
        disallowRedundantWrapping: true,
      },
    ],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'symbol-description': 'error',
    'unicode-bom': ['error', 'never'],
    'use-isnan': [
      'error',
      {
        enforceForIndexOf: true,
        enforceForSwitchCase: true,
      },
    ],
    'valid-typeof': [
      'error',
      {
        requireStringLiterals: true,
      },
    ],
    'vars-on-top': 'error',
    yoda: ['error', 'never'],
    'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
    'import/first': 'error',
    'import/no-duplicates': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-named-default': 'error',
    'import/no-unassigned-import': 'off',
    'import/newline-after-import': [
      'error',
      {
        count: 1,
      },
    ],
    'no-unassigned-vars': 'warn',
    'preserve-caught-error': 'warn',
    'react/react-in-jsx-scope': 'off',
    'jsx-a11y/anchor-has-content': 'warn',
    'jsx-a11y/click-events-have-key-events': 'warn',
    'jsx-a11y/control-has-associated-label': 'warn',
    'jsx-a11y/interactive-supports-focus': 'warn',
    'jsx-a11y/label-has-associated-control': 'warn',
    'jsx-a11y/mouse-events-have-key-events': 'warn',
    'jsx-a11y/no-autofocus': 'off',
    'jsx-a11y/no-noninteractive-element-interactions': 'warn',
    'jsx-a11y/no-noninteractive-tabindex': 'warn',
    'jsx-a11y/no-redundant-roles': 'warn',
    'jsx-a11y/no-static-element-interactions': 'warn',
    'jsx-a11y/prefer-tag-over-role': 'warn',
    'react/rules-of-hooks': 'error',
    'better-tailwindcss/enforce-consistent-class-order': 'off',
    'better-tailwindcss/enforce-consistent-line-wrapping': 'off',
    'better-tailwindcss/no-deprecated-classes': 'error',
    'better-tailwindcss/no-duplicate-classes': 'error',
    'better-tailwindcss/no-unnecessary-whitespace': 'off',
    'better-tailwindcss/enforce-canonical-classes': 'error',
    'better-tailwindcss/no-conflicting-classes': 'error',
    'better-tailwindcss/no-unknown-classes': [
      'error',
      {
        ignore: [
          'toaster',
          'typography',
          'typography-disabled',
          'bg-fd-secondary',
          'text-fd-secondary-foreground',
          'text-fd-muted-foreground',
          'fd-scroll-container',
          'placeholder:text-fd-muted-foreground',
          'text-fd-primary',
          'text-fd-error',
          'bg-fd-overlay',
          'animate-fd-fade-in',
          'animate-fd-fade-out',
          'bg-fd-card',
          'text-fd-card-foreground',
          'animate-fd-dialog-in',
          'animate-fd-dialog-out',
          'text-fd-muted-foreground/80',
          'focus-visible:ring-fd-ring',
        ],
      },
    ],
    'typescript/no-explicit-any': 'error',
  },
  overrides: [
    {
      files: ['**/*.?([cm])[jt]s?(x)'],
      rules: {
        'node/handle-callback-err': ['error', '^(err|error)$'],
        'node/no-exports-assign': 'error',
        'node/no-new-require': 'error',
        'node/no-path-concat': 'error',
        'jsdoc/check-access': 'warn',
        'jsdoc/check-property-names': 'warn',
        'jsdoc/empty-tags': 'warn',
        'jsdoc/implements-on-classes': 'warn',
        'jsdoc/no-defaults': 'warn',
        'jsdoc/require-param-name': 'warn',
        'jsdoc/require-property': 'warn',
        'jsdoc/require-property-description': 'warn',
        'jsdoc/require-property-name': 'warn',
        'jsdoc/require-returns-description': 'warn',
        'unicorn/consistent-empty-array-spread': 'error',
        'unicorn/error-message': 'error',
        'unicorn/escape-case': 'error',
        'unicorn/new-for-builtins': 'error',
        'unicorn/no-instanceof-builtins': 'error',
        'unicorn/no-new-array': 'error',
        'unicorn/no-new-buffer': 'error',
        'unicorn/number-literal-case': 'error',
        'unicorn/prefer-dom-node-text-content': 'error',
        'unicorn/prefer-includes': 'error',
        'unicorn/prefer-node-protocol': 'error',
        'unicorn/prefer-number-properties': 'error',
        'unicorn/prefer-string-starts-ends-with': 'error',
        'unicorn/prefer-type-error': 'error',
        'unicorn/throw-new-error': 'error',
      },
      plugins: ['node', 'jsdoc', 'unicorn'],
    },
    {
      files: ['**/*.?([cm])ts', '**/*.?([cm])tsx'],
      rules: {
        'constructor-super': 'off',
        'getter-return': 'off',
        'no-class-assign': 'off',
        'no-const-assign': 'off',
        'no-dupe-keys': 'off',
        'no-func-assign': 'off',
        'no-import-assign': 'off',
        'no-new-native-nonconstructor': 'off',
        'no-obj-calls': 'off',
        'no-redeclare': [
          'error',
          {
            builtinGlobals: false,
          },
        ],
        'no-setter-return': 'off',
        'no-this-before-super': 'off',
        'no-unreachable': 'off',
        'no-unsafe-negation': 'off',
        'no-with': 'off',
        'prefer-const': [
          'error',
          {
            destructuring: 'all',
            ignoreReadBeforeAssign: true,
          },
        ],
        'no-unused-expressions': [
          'error',
          {
            allowShortCircuit: true,
            allowTaggedTemplates: true,
            allowTernary: true,
          },
        ],
        'no-unused-vars': 'off',
        'no-useless-constructor': 'off',
        'no-use-before-define': [
          'error',
          {
            classes: false,
            functions: false,
            variables: true,
          },
        ],
        'typescript/ban-ts-comment': [
          'error',
          {
            'ts-expect-error': 'allow-with-description',
          },
        ],
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-dynamic-delete': 'off',
        'typescript/no-empty-object-type': [
          'error',
          {
            allowInterfaces: 'always',
          },
        ],
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-extraneous-class': 'off',
        'typescript/no-invalid-void-type': 'off',
        'typescript/no-misused-new': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-nullish-coalescing': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-non-null-assertion': 'off',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-literal-enum-member': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/triple-slash-reference': 'off',
        'typescript/unified-signatures': 'off',
        'typescript/consistent-type-definitions': ['error', 'interface'],
        'typescript/consistent-type-imports': [
          'error',
          {
            disallowTypeAnnotations: false,
            fixStyle: 'separate-type-imports',
            prefer: 'type-imports',
          },
        ],
        'typescript/method-signature-style': ['error', 'property'],
        'typescript/no-import-type-side-effects': 'error',
      },
    },
    {
      files: [
        '**/__tests__/**/*.?([cm])[jt]s?(x)',
        '**/*.spec.?([cm])[jt]s?(x)',
        '**/*.test.?([cm])[jt]s?(x)',
        '**/*.bench.?([cm])[jt]s?(x)',
        '**/*.benchmark.?([cm])[jt]s?(x)',
      ],
      rules: {
        'vitest/consistent-test-it': [
          'error',
          {
            fn: 'it',
            withinDescribe: 'it',
          },
        ],
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        'vitest/prefer-hooks-in-order': 'error',
        'vitest/prefer-lowercase-title': 'error',
        'no-unused-expressions': 'off',
        'typescript/explicit-function-return-type': 'off',
      },
      plugins: ['vitest'],
    },
    {
      files: ['**/*.?([cm])[jt]s?(x)'],
      rules: {
        'react/no-array-index-key': 'warn',
        'react/no-clone-element': 'warn',
        'react/no-direct-mutation-state': 'error',
        'react/jsx-no-comment-textnodes': 'warn',
        'react/only-export-components': [
          'error',
          {
            allowConstantExport: false,
            allowExportNames: [],
          },
        ],
      },
    },
    {
      files: ['**/*.md/**/*.?([cm])[jt]s?(x)'],
      rules: {
        'no-alert': 'off',
        'no-labels': 'off',
        'no-lone-blocks': 'off',
        'no-unused-expressions': 'off',
        'no-unused-labels': 'off',
        'no-unused-vars': 'off',
        'unicode-bom': 'off',
        'no-redeclare': 'off',
        'no-use-before-define': 'off',
        'typescript/consistent-type-imports': 'off',
        'typescript/explicit-function-return-type': 'off',
        'typescript/no-namespace': 'off',
        'typescript/no-require-imports': 'off',
      },
    },
    {
      files: ['**/scripts/**/*.?([cm])[jt]s?(x)'],
      rules: {
        'typescript/explicit-function-return-type': 'off',
      },
    },
    {
      files: ['**/*.js', '**/*.cjs'],
      rules: {
        'typescript/no-require-imports': 'off',
      },
    },
    {
      files: ['**/*.config.?([cm])[jt]s?(x)', '**/*.config.*.?([cm])[jt]s?(x)'],
      rules: {
        'typescript/explicit-function-return-type': 'off',
      },
    },
    {
      files: ['**/e2e/**/*'],
      rules: {
        'react/rules-of-hooks': 'off',
      },
    },
    {
      files: ['**/monaco-worker.ts'],
      rules: {
        'import/default': 'off',
      },
    },
  ],
})
