catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - packages/*
  - apps/*
catalog:
  '@ai-sdk/anthropic': ^3.0.17
  '@ai-sdk/google': ^3.0.10
  '@ai-sdk/openai': ^3.0.13
  '@ai-sdk/provider': ^3.0.4
  '@ai-sdk/react': ^3.0.45
  '@ai-sdk/xai': ^3.0.29
  '@antfu/eslint-config': ^7.2.0
  '@base-ui/react': ^1.1.0
  '@clickhouse/client': ^1.16.0
  '@commitlint/cli': ^20.3.1
  '@commitlint/config-conventional': ^20.3.1
  '@dagrejs/dagre': 1.1.8
  '@electric-sql/pglite': ^0.3.15
  '@eslint-react/eslint-plugin': ^2.7.2
  '@exalabs/ai-sdk': ^1.0.5
  '@faker-js/faker': ^10.2.0
  '@fluentui/react-context-selector': ^9.2.13
  '@hono/arktype-validator': ^2.0.1
  '@monaco-editor/loader': ^1.7.0
  '@number-flow/react': ^0.5.11
  '@octokit/rest': ^22.0.1
  '@orpc/client': ^1.13.4
  '@orpc/contract': ^1.13.4
  '@orpc/server': ^1.13.4
  '@orpc/tanstack-query': ^1.13.4
  '@playwright/test': ^1.57.0
  '@posthog/ai': ^7.5.3
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@react-email/components': ^1.0.6
  '@remixicon/react': ^4.8.0
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-db': ^0.1.66
  '@tanstack/react-devtools': ^0.9.2
  '@tanstack/react-form': ^1.27.7
  '@tanstack/react-query': ^5.90.19
  '@tanstack/react-query-devtools': ^5.91.2
  '@tanstack/react-router': ^1.154.1
  '@tanstack/react-router-devtools': ^1.154.1
  '@tanstack/react-start': ^1.154.1
  '@tanstack/react-store': ^0.8.0
  '@tanstack/react-virtual': ^3.13.18
  '@tanstack/router-plugin': ^1.154.1
  '@tiptap/extension-placeholder': ^3.16.0
  '@tiptap/react': ^3.16.0
  '@tiptap/starter-kit': ^3.16.0
  '@todesktop/cli': ^1.19.1
  '@todesktop/runtime': ^2.1.3
  '@toon-format/toon': ^2.1.0
  '@types/bun': ^1.3.6
  '@types/ioredis-mock': ^8.2.6
  '@types/mssql': ^9.1.9
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@upstash/context7-tools-ai-sdk': ^0.2.1
  '@vitejs/plugin-react': ^5.1.2
  '@xyflow/react': ^12.10.0
  ai: ^6.0.43
  ai-retry: ^1.0.2
  arkregex: ^0.0.5
  arktype: ^2.1.29
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.4.17
  better-auth-harmony: ^1.2.5
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  consola: ^3.4.2
  cross-env: ^10.1.0
  date-fns: ^4.1.0
  drizzle-arktype: ^0.1.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  electron: 39.2.6
  electron-builder: ^26.4.0
  electron-store: ^11.0.2
  electron-vite: ^5.0.0
  eslint: ^9.39.2
  eslint-plugin-better-tailwindcss: ^4.0.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  hono: ^4.11.4
  hookable: ^6.0.1
  husky: ^9.1.7
  input-otp: ^1.4.2
  ioredis: ^5.9.2
  ioredis-mock: ^8.13.1
  js-base64: ^3.7.8
  js-confetti: ^0.13.1
  kysely: ^0.28.10
  lucide-react: ^0.562.0
  marked: ^17.0.1
  monaco-editor: ^0.54.0
  monaco-sql-languages: ^0.15.1
  monaco-themes: ^0.4.8
  monacopilot: ^1.2.12
  motion: ^12.28.1
  mssql: ^12.2.0
  mysql2: ^3.16.1
  nanoid: ^5.1.6
  nitro: ^3.0.1-alpha.1
  npm-run-all2: ^8.0.4
  pg: ^8.17.2
  playwright: ^1.57.0
  postgres: ^3.4.8
  posthog-js: ^1.333.0
  posthog-node: ^5.24.1
  react: ^19.2.3
  react-dom: ^19.2.3
  react-markdown: ^10.1.0
  react-resizable-panels: ^4.4.1
  react-scan: ^0.4.3
  redis: ^5.10.0
  remark-gfm: ^4.0.1
  resend: ^6.8.0
  resumable-stream: ^2.2.10
  sonner: ^2.0.7
  sql-formatter: ^15.7.0
  streamdown: ^2.1.0
  stripe: ^20.2.0
  superjson: ^2.2.6
  tailwind-merge: ^3.4.0
  tailwind-scrollbar: ^4.0.2
  tailwindcss: ^4.1.18
  tanstack-db-pglite: ^1.0.5
  taze: ^19.9.2
  tsx: ^4.21.0
  turbo: ^2.7.5
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  ua-parser-js: ^2.0.8
  use-stick-to-bottom: ^1.1.1
  uuid: ^13.0.0
  vite: ^7.3.1
  vite-tsconfig-paths: ^6.0.4
  zod: ^4.3.5

ignoredBuiltDependencies:
  - '@firebase/util'
  - core-js
  - dtrace-provider
  - esbuild
  - protobufjs
onlyBuiltDependencies:
  - electron
  - electron-winstaller
