catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - packages/*
  - apps/*
catalog:
  '@ai-sdk/anthropic': ^2.0.54
  '@ai-sdk/google': ^2.0.45
  '@ai-sdk/openai': ^2.0.80
  '@ai-sdk/provider': ^2.0.0
  '@ai-sdk/react': ^2.0.109
  '@ai-sdk/xai': ^2.0.39
  '@antfu/eslint-config': ^6.5.1
  '@base-ui-components/react': ^1.0.0-rc.0
  '@clickhouse/client': ^1.14.0
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@dagrejs/dagre': 1.1.8
  '@databuddy/sdk': ^2.3.1
  '@electric-sql/pglite': ^0.3.14
  '@eslint-react/eslint-plugin': ^2.3.13
  '@exalabs/ai-sdk': ^1.0.5
  '@faker-js/faker': ^10.1.0
  '@fluentui/react-context-selector': ^9.2.12
  '@hono/arktype-validator': ^2.0.1
  '@monaco-editor/loader': ^1.7.0
  '@number-flow/react': ^0.5.10
  '@octokit/rest': ^22.0.1
  '@orpc/client': ^1.12.2
  '@orpc/contract': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@playwright/test': ^1.57.0
  '@posthog/ai': ^7.2.1
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@react-email/components': ^1.0.1
  '@remixicon/react': ^4.7.0
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-db': ^0.1.55
  '@tanstack/react-devtools': ^0.8.4
  '@tanstack/react-form': ^1.27.1
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-router': ^1.140.1
  '@tanstack/react-router-devtools': ^1.140.1
  '@tanstack/react-start': ^1.140.1
  '@tanstack/react-store': ^0.8.0
  '@tanstack/react-virtual': ^3.13.13
  '@tanstack/router-plugin': ^1.140.1
  '@tiptap/extension-placeholder': ^3.13.0
  '@tiptap/react': ^3.13.0
  '@tiptap/starter-kit': ^3.13.0
  '@todesktop/cli': ^1.18.0
  '@todesktop/runtime': ^2.1.3
  '@toon-format/toon': ^2.1.0
  '@types/bun': ^1.3.4
  '@types/ioredis-mock': ^8.2.6
  '@types/mssql': ^9.1.8
  '@types/pg': ^8.15.6
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  '@xyflow/react': ^12.10.0
  ai: ^5.0.108
  ai-retry: ^0.11.0
  arkregex: ^0.0.4
  arktype: ^2.1.28
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.4.5
  better-auth-harmony: ^1.2.5
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  consola: ^3.4.2
  cross-env: ^10.1.0
  date-fns: ^4.1.0
  dayjs: ^1.11.19
  drizzle-arktype: ^0.1.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.0
  electron: ^39.2.6
  electron-builder: ^26.0.12
  electron-store: ^11.0.2
  electron-updater: ^6.6.2
  electron-vite: ^5.0.0
  eslint: ^9.39.1
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  hono: ^4.10.8
  hookable: ^5.5.3
  husky: ^9.1.7
  input-otp: ^1.4.2
  ioredis: ^5.8.2
  ioredis-mock: ^8.13.1
  js-base64: ^3.7.8
  kysely: ^0.28.8
  loops: ^6.0.1
  lucide-react: ^0.556.0
  marked: ^17.0.1
  monaco-editor: ^0.54.0
  monaco-sql-languages: ^0.15.1
  monaco-themes: ^0.4.8
  motion: ^12.23.25
  mssql: ^12.2.0
  mysql2: ^3.15.3
  nanoid: ^5.1.6
  nitro: ^3.0.1-alpha.1
  npm-run-all2: ^8.0.4
  pg: ^8.16.3
  playwright: ^1.57.0
  postgres: ^3.4.7
  posthog-js: ^1.302.2
  posthog-node: ^5.17.2
  react: ^19.2.1
  react-dom: ^19.2.1
  react-markdown: ^10.1.0
  react-resizable-panels: ^3.0.6
  react-scan: ^0.4.3
  redis: ^5.10.0
  remark-gfm: ^4.0.1
  resend: ^6.6.0
  resumable-stream: ^2.2.8
  sonner: ^2.0.7
  sql-formatter: ^15.6.10
  stripe: ^20.0.0
  superjson: ^2.2.6
  tailwind-merge: ^3.4.0
  tailwind-scrollbar: ^4.0.2
  tailwindcss: ^4.1.17
  tanstack-db-pglite: ^1.0.5
  taze: ^19.9.2
  tsx: ^4.21.0
  turbo: ^2.6.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  use-stick-to-bottom: ^1.1.1
  uuid: ^13.0.0
  vite: ^7.2.7
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.1.13
onlyBuiltDependencies:
  - electron
