packages:
  - packages/*
  - apps/*

catalog:
  '@number-flow/react': ^0.5.10
  '@remixicon/react': ^4.6.0
  '@tanstack/react-query': ^5.85.9
  '@tanstack/react-query-devtools': ^5.85.9
  '@tanstack/react-router': ^1.131.32
  '@tanstack/react-router-devtools': ^1.131.32
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  ai: ^5.0.30
  arktype: 2.1.20
  babel-plugin-react-compiler: 19.1.0-rc.2
  better-auth: ^1.3.7
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  nanoid: ^5.1.5
  react: ^19.1.1
  react-dom: ^19.1.1
  sonner: ^2.0.7
  tailwindcss: ^4.1.12
  tw-animate-css: ^1.3.7
  typescript: ^5.9.2
  uuid: ^11.1.0
  vite: ^7.1.4
  zod: ^4.1.5

onlyBuiltDependencies:
  - electron
