packages:
  - packages/*
  - apps/*

catalog:
  '@number-flow/react': ^0.5.10
  '@orpc/client': ^1.10.3
  '@orpc/server': ^1.10.3
  '@playwright/test': ^1.56.1
  '@remixicon/react': ^4.7.0
  '@tanstack/react-query': ^5.90.6
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router': ^1.134.9
  '@tanstack/react-router-devtools': ^1.134.9
  '@tanstack/react-store': ^0.8.0
  '@tanstack/react-virtual': ^3.13.12
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react': ^5.1.0
  '@xyflow/react': ^12.9.2
  ai: ^5.0.86
  arktype: 2.1.20
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.3.17
  drizzle-kit: ^0.31.6
  drizzle-orm: 0.44.5
  monaco-editor: ^0.54.0
  motion: ^12.23.24
  nanoid: ^5.1.6
  react: ^19.2.0
  react-dom: ^19.2.0
  sonner: ^2.0.7
  tailwindcss: ^4.1.16
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: ^7.1.12
  zod: ^4.1.12

onlyBuiltDependencies:
  - electron
