packages:
  - packages/*
  - apps/*

catalog:
  '@number-flow/react': ^0.5.10
  '@orpc/client': ^1.9.3
  '@orpc/server': ^1.9.3
  '@playwright/test': ^1.56.0
  '@remixicon/react': ^4.6.0
  '@tanstack/react-query': ^5.90.2
  '@tanstack/react-query-devtools': ^5.90.2
  '@tanstack/react-router': ^1.132.47
  '@tanstack/react-router-devtools': ^1.132.47
  '@tanstack/react-virtual': ^3.13.12
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  '@vitejs/plugin-react': ^5.0.4
  '@xyflow/react': ^12.8.6
  ai: ^5.0.60
  arktype: 2.1.20
  babel-plugin-react-compiler: 19.1.0-rc.2
  better-auth: ^1.3.17
  drizzle-kit: ^0.31.5
  drizzle-orm: 0.44.5
  motion: ^12.23.22
  nanoid: ^5.1.6
  react: ^19.2.0
  react-dom: ^19.2.0
  sonner: ^2.0.7
  tailwindcss: ^4.1.14
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: ^7.1.9
  zod: ^4.1.12

onlyBuiltDependencies:
  - electron
