import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { MuseoModerno, Nunito_Sans } from 'next/font/google'
import '~/app/index.css'

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
})

const museoModerno = MuseoModerno({
  variable: '--font-museo-moderno',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-sans ${nunitoSans.variable} ${museoModerno.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
