/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedConnectionResourceIdRouteImport } from './routes/_protected/connection/$resourceId'
import { Route as ProtectedCreateIndexRouteImport } from './routes/_protected/create/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSettingsAppearanceRouteImport } from './routes/_protected/settings/appearance'
import { Route as ProtectedSettingsGeneralRouteImport } from './routes/_protected/settings/general'
import { Route as ProtectedSettingsMcpRouteImport } from './routes/_protected/settings/mcp'
import { Route as ProtectedSettingsPrivacyRouteImport } from './routes/_protected/settings/privacy'
import { Route as ProtectedConnectionResourceIdIndexRouteImport } from './routes/_protected/connection/$resourceId/index'
import { Route as ProtectedConnectionResourceIdTabIdRouteImport } from './routes/_protected/connection/$resourceId/$tabId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConnectionResourceIdRoute =
  ProtectedConnectionResourceIdRouteImport.update({
    id: '/connection/$resourceId',
    path: '/connection/$resourceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCreateIndexRoute = ProtectedCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsAppearanceRoute =
  ProtectedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsGeneralRoute =
  ProtectedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsMcpRoute = ProtectedSettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedSettingsPrivacyRoute =
  ProtectedSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedConnectionResourceIdIndexRoute =
  ProtectedConnectionResourceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedConnectionResourceIdRoute,
  } as any)
const ProtectedConnectionResourceIdTabIdRoute =
  ProtectedConnectionResourceIdTabIdRouteImport.update({
    id: '/$tabId',
    path: '/$tabId',
    getParentRoute: () => ProtectedConnectionResourceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/connection/$resourceId': typeof ProtectedConnectionResourceIdRouteWithChildren
  '/settings/appearance': typeof ProtectedSettingsAppearanceRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/mcp': typeof ProtectedSettingsMcpRoute
  '/settings/privacy': typeof ProtectedSettingsPrivacyRoute
  '/create/': typeof ProtectedCreateIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/connection/$resourceId/$tabId': typeof ProtectedConnectionResourceIdTabIdRoute
  '/connection/$resourceId/': typeof ProtectedConnectionResourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof ProtectedIndexRoute
  '/settings/appearance': typeof ProtectedSettingsAppearanceRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/mcp': typeof ProtectedSettingsMcpRoute
  '/settings/privacy': typeof ProtectedSettingsPrivacyRoute
  '/create': typeof ProtectedCreateIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/connection/$resourceId/$tabId': typeof ProtectedConnectionResourceIdTabIdRoute
  '/connection/$resourceId': typeof ProtectedConnectionResourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/connection/$resourceId': typeof ProtectedConnectionResourceIdRouteWithChildren
  '/_protected/settings/appearance': typeof ProtectedSettingsAppearanceRoute
  '/_protected/settings/general': typeof ProtectedSettingsGeneralRoute
  '/_protected/settings/mcp': typeof ProtectedSettingsMcpRoute
  '/_protected/settings/privacy': typeof ProtectedSettingsPrivacyRoute
  '/_protected/create/': typeof ProtectedCreateIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/connection/$resourceId/$tabId': typeof ProtectedConnectionResourceIdTabIdRoute
  '/_protected/connection/$resourceId/': typeof ProtectedConnectionResourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/connection/$resourceId'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/mcp'
    | '/settings/privacy'
    | '/create/'
    | '/settings/'
    | '/connection/$resourceId/$tabId'
    | '/connection/$resourceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/mcp'
    | '/settings/privacy'
    | '/create'
    | '/settings'
    | '/connection/$resourceId/$tabId'
    | '/connection/$resourceId'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/connection/$resourceId'
    | '/_protected/settings/appearance'
    | '/_protected/settings/general'
    | '/_protected/settings/mcp'
    | '/_protected/settings/privacy'
    | '/_protected/create/'
    | '/_protected/settings/'
    | '/_protected/connection/$resourceId/$tabId'
    | '/_protected/connection/$resourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/connection/$resourceId': {
      id: '/_protected/connection/$resourceId'
      path: '/connection/$resourceId'
      fullPath: '/connection/$resourceId'
      preLoaderRoute: typeof ProtectedConnectionResourceIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create/': {
      id: '/_protected/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof ProtectedCreateIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/appearance': {
      id: '/_protected/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof ProtectedSettingsAppearanceRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/general': {
      id: '/_protected/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ProtectedSettingsGeneralRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/mcp': {
      id: '/_protected/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof ProtectedSettingsMcpRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/privacy': {
      id: '/_protected/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof ProtectedSettingsPrivacyRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/connection/$resourceId/': {
      id: '/_protected/connection/$resourceId/'
      path: '/'
      fullPath: '/connection/$resourceId/'
      preLoaderRoute: typeof ProtectedConnectionResourceIdIndexRouteImport
      parentRoute: typeof ProtectedConnectionResourceIdRoute
    }
    '/_protected/connection/$resourceId/$tabId': {
      id: '/_protected/connection/$resourceId/$tabId'
      path: '/$tabId'
      fullPath: '/connection/$resourceId/$tabId'
      preLoaderRoute: typeof ProtectedConnectionResourceIdTabIdRouteImport
      parentRoute: typeof ProtectedConnectionResourceIdRoute
    }
  }
}

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsAppearanceRoute: typeof ProtectedSettingsAppearanceRoute
  ProtectedSettingsGeneralRoute: typeof ProtectedSettingsGeneralRoute
  ProtectedSettingsMcpRoute: typeof ProtectedSettingsMcpRoute
  ProtectedSettingsPrivacyRoute: typeof ProtectedSettingsPrivacyRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsAppearanceRoute: ProtectedSettingsAppearanceRoute,
  ProtectedSettingsGeneralRoute: ProtectedSettingsGeneralRoute,
  ProtectedSettingsMcpRoute: ProtectedSettingsMcpRoute,
  ProtectedSettingsPrivacyRoute: ProtectedSettingsPrivacyRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedConnectionResourceIdRouteChildren {
  ProtectedConnectionResourceIdTabIdRoute: typeof ProtectedConnectionResourceIdTabIdRoute
  ProtectedConnectionResourceIdIndexRoute: typeof ProtectedConnectionResourceIdIndexRoute
}

const ProtectedConnectionResourceIdRouteChildren: ProtectedConnectionResourceIdRouteChildren =
  {
    ProtectedConnectionResourceIdTabIdRoute:
      ProtectedConnectionResourceIdTabIdRoute,
    ProtectedConnectionResourceIdIndexRoute:
      ProtectedConnectionResourceIdIndexRoute,
  }

const ProtectedConnectionResourceIdRouteWithChildren =
  ProtectedConnectionResourceIdRoute._addFileChildren(
    ProtectedConnectionResourceIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedConnectionResourceIdRoute: typeof ProtectedConnectionResourceIdRouteWithChildren
  ProtectedCreateIndexRoute: typeof ProtectedCreateIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedConnectionResourceIdRoute:
    ProtectedConnectionResourceIdRouteWithChildren,
  ProtectedCreateIndexRoute: ProtectedCreateIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
