/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedConnectionResourceIdRouteImport } from './routes/_protected/connection/$resourceId'
import { Route as ProtectedCreateIndexRouteImport } from './routes/_protected/create/index'
import { Route as ProtectedConnectionResourceIdIndexRouteImport } from './routes/_protected/connection/$resourceId/index'
import { Route as ProtectedConnectionResourceIdTabIdRouteImport } from './routes/_protected/connection/$resourceId/$tabId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConnectionResourceIdRoute =
  ProtectedConnectionResourceIdRouteImport.update({
    id: '/connection/$resourceId',
    path: '/connection/$resourceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCreateIndexRoute = ProtectedCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConnectionResourceIdIndexRoute =
  ProtectedConnectionResourceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedConnectionResourceIdRoute,
  } as any)
const ProtectedConnectionResourceIdTabIdRoute =
  ProtectedConnectionResourceIdTabIdRouteImport.update({
    id: '/$tabId',
    path: '/$tabId',
    getParentRoute: () => ProtectedConnectionResourceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRoute
  '/connection/$resourceId': typeof ProtectedConnectionResourceIdRouteWithChildren
  '/create/': typeof ProtectedCreateIndexRoute
  '/connection/$resourceId/$tabId': typeof ProtectedConnectionResourceIdTabIdRoute
  '/connection/$resourceId/': typeof ProtectedConnectionResourceIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof ProtectedIndexRoute
  '/create': typeof ProtectedCreateIndexRoute
  '/connection/$resourceId/$tabId': typeof ProtectedConnectionResourceIdTabIdRoute
  '/connection/$resourceId': typeof ProtectedConnectionResourceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/connection/$resourceId': typeof ProtectedConnectionResourceIdRouteWithChildren
  '/_protected/create/': typeof ProtectedCreateIndexRoute
  '/_protected/connection/$resourceId/$tabId': typeof ProtectedConnectionResourceIdTabIdRoute
  '/_protected/connection/$resourceId/': typeof ProtectedConnectionResourceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connection/$resourceId'
    | '/create/'
    | '/connection/$resourceId/$tabId'
    | '/connection/$resourceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/create'
    | '/connection/$resourceId/$tabId'
    | '/connection/$resourceId'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/'
    | '/_protected/connection/$resourceId'
    | '/_protected/create/'
    | '/_protected/connection/$resourceId/$tabId'
    | '/_protected/connection/$resourceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/connection/$resourceId': {
      id: '/_protected/connection/$resourceId'
      path: '/connection/$resourceId'
      fullPath: '/connection/$resourceId'
      preLoaderRoute: typeof ProtectedConnectionResourceIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/create/': {
      id: '/_protected/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof ProtectedCreateIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/connection/$resourceId/': {
      id: '/_protected/connection/$resourceId/'
      path: '/'
      fullPath: '/connection/$resourceId/'
      preLoaderRoute: typeof ProtectedConnectionResourceIdIndexRouteImport
      parentRoute: typeof ProtectedConnectionResourceIdRoute
    }
    '/_protected/connection/$resourceId/$tabId': {
      id: '/_protected/connection/$resourceId/$tabId'
      path: '/$tabId'
      fullPath: '/connection/$resourceId/$tabId'
      preLoaderRoute: typeof ProtectedConnectionResourceIdTabIdRouteImport
      parentRoute: typeof ProtectedConnectionResourceIdRoute
    }
  }
}

interface ProtectedConnectionResourceIdRouteChildren {
  ProtectedConnectionResourceIdTabIdRoute: typeof ProtectedConnectionResourceIdTabIdRoute
  ProtectedConnectionResourceIdIndexRoute: typeof ProtectedConnectionResourceIdIndexRoute
}

const ProtectedConnectionResourceIdRouteChildren: ProtectedConnectionResourceIdRouteChildren =
  {
    ProtectedConnectionResourceIdTabIdRoute:
      ProtectedConnectionResourceIdTabIdRoute,
    ProtectedConnectionResourceIdIndexRoute:
      ProtectedConnectionResourceIdIndexRoute,
  }

const ProtectedConnectionResourceIdRouteWithChildren =
  ProtectedConnectionResourceIdRoute._addFileChildren(
    ProtectedConnectionResourceIdRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedConnectionResourceIdRoute: typeof ProtectedConnectionResourceIdRouteWithChildren
  ProtectedCreateIndexRoute: typeof ProtectedCreateIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedConnectionResourceIdRoute:
    ProtectedConnectionResourceIdRouteWithChildren,
  ProtectedCreateIndexRoute: ProtectedCreateIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
