/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as OpenRouteImport } from './modules/deep-link/routes/open'
import { Route as AuthEmailCodeRouteImport } from './routes/_auth/email-code'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDownloadRouteImport } from './routes/_layout/download'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutPrivacyPolicyRouteImport } from './modules/legal/routes/_layout/privacy-policy'
import { Route as LayoutReleasesRouteImport } from './modules/releases/routes/_layout/releases'
import { Route as LayoutTermsOfServiceRouteImport } from './modules/legal/routes/_layout/terms-of-service'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as DeepDotsignInRouteImport } from './modules/deep-link/routes/deep.sign-in'

const AccountAiUsageDotlazyRouteImport = createFileRoute('/account/ai-usage')()
const AccountApiKeysDotlazyRouteImport = createFileRoute('/account/api-keys')()
const AccountBillingDotlazyRouteImport = createFileRoute('/account/billing')()
const AccountSettingsIndexDotlazyRouteImport =
  createFileRoute('/account/settings/')()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailCodeRoute = AuthEmailCodeRouteImport.update({
  id: '/email-code',
  path: '/email-code',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDownloadRoute = LayoutDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyPolicyRoute = LayoutPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./modules/legal/routes/_layout/privacy-policy.lazy').then(
    (d) => d.Route,
  ),
)
const LayoutReleasesRoute = LayoutReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTermsOfServiceRoute = LayoutTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./modules/legal/routes/_layout/terms-of-service.lazy').then(
    (d) => d.Route,
  ),
)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAiUsageDotlazyRoute = AccountAiUsageDotlazyRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./modules/ai-usage/routes/account/ai-usage.lazy').then(
    (d) => d.Route,
  ),
)
const AccountApiKeysDotlazyRoute = AccountApiKeysDotlazyRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./modules/api-keys/routes/account/api-keys.lazy').then(
    (d) => d.Route,
  ),
)
const AccountBillingDotlazyRoute = AccountBillingDotlazyRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./modules/billing/routes/account/billing.lazy').then((d) => d.Route),
)
const DeepDotsignInRoute = DeepDotsignInRouteImport.update({
  id: '/deep/sign-in',
  path: '/deep/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsIndexDotlazyRoute =
  AccountSettingsIndexDotlazyRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AccountRoute,
  } as any).lazy(() =>
    import('./modules/settings/routes/account/settings/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/open': typeof OpenRoute
  '/email-code': typeof AuthEmailCodeRoute
  '/sign-in': typeof AuthSignInRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/download': typeof LayoutDownloadRoute
  '/home': typeof LayoutHomeRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/releases': typeof LayoutReleasesRoute
  '/terms-of-service': typeof LayoutTermsOfServiceRoute
  '/deep/sign-in': typeof DeepDotsignInRoute
  '/account/ai-usage': typeof AccountAiUsageDotlazyRoute
  '/account/api-keys': typeof AccountApiKeysDotlazyRoute
  '/account/billing': typeof AccountBillingDotlazyRoute
  '/account/': typeof AccountIndexRoute
  '/account/settings/': typeof AccountSettingsIndexDotlazyRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/open': typeof OpenRoute
  '/email-code': typeof AuthEmailCodeRoute
  '/sign-in': typeof AuthSignInRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/download': typeof LayoutDownloadRoute
  '/home': typeof LayoutHomeRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/releases': typeof LayoutReleasesRoute
  '/terms-of-service': typeof LayoutTermsOfServiceRoute
  '/deep/sign-in': typeof DeepDotsignInRoute
  '/account/ai-usage': typeof AccountAiUsageDotlazyRoute
  '/account/api-keys': typeof AccountApiKeysDotlazyRoute
  '/account/billing': typeof AccountBillingDotlazyRoute
  '/account': typeof AccountIndexRoute
  '/account/settings': typeof AccountSettingsIndexDotlazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/open': typeof OpenRoute
  '/_auth/email-code': typeof AuthEmailCodeRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_layout/download': typeof LayoutDownloadRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/_layout/releases': typeof LayoutReleasesRoute
  '/_layout/terms-of-service': typeof LayoutTermsOfServiceRoute
  '/deep/sign-in': typeof DeepDotsignInRoute
  '/account/ai-usage': typeof AccountAiUsageDotlazyRoute
  '/account/api-keys': typeof AccountApiKeysDotlazyRoute
  '/account/billing': typeof AccountBillingDotlazyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/account/': typeof AccountIndexRoute
  '/account/settings/': typeof AccountSettingsIndexDotlazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/open'
    | '/email-code'
    | '/sign-in'
    | '/two-factor'
    | '/download'
    | '/home'
    | '/privacy-policy'
    | '/releases'
    | '/terms-of-service'
    | '/deep/sign-in'
    | '/account/ai-usage'
    | '/account/api-keys'
    | '/account/billing'
    | '/account/'
    | '/account/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/open'
    | '/email-code'
    | '/sign-in'
    | '/two-factor'
    | '/download'
    | '/home'
    | '/privacy-policy'
    | '/releases'
    | '/terms-of-service'
    | '/deep/sign-in'
    | '/account/ai-usage'
    | '/account/api-keys'
    | '/account/billing'
    | '/account'
    | '/account/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/account'
    | '/open'
    | '/_auth/email-code'
    | '/_auth/sign-in'
    | '/_auth/two-factor'
    | '/_layout/download'
    | '/_layout/home'
    | '/_layout/privacy-policy'
    | '/_layout/releases'
    | '/_layout/terms-of-service'
    | '/deep/sign-in'
    | '/account/ai-usage'
    | '/account/api-keys'
    | '/account/billing'
    | '/_layout/'
    | '/account/'
    | '/account/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  OpenRoute: typeof OpenRoute
  DeepDotsignInRoute: typeof DeepDotsignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/email-code': {
      id: '/_auth/email-code'
      path: '/email-code'
      fullPath: '/email-code'
      preLoaderRoute: typeof AuthEmailCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/download': {
      id: '/_layout/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof LayoutDownloadRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy-policy': {
      id: '/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPrivacyPolicyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/releases': {
      id: '/_layout/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof LayoutReleasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/terms-of-service': {
      id: '/_layout/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LayoutTermsOfServiceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/ai-usage': {
      id: '/account/ai-usage'
      path: '/ai-usage'
      fullPath: '/account/ai-usage'
      preLoaderRoute: typeof AccountAiUsageDotlazyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/api-keys': {
      id: '/account/api-keys'
      path: '/api-keys'
      fullPath: '/account/api-keys'
      preLoaderRoute: typeof AccountApiKeysDotlazyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingDotlazyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/deep/sign-in': {
      id: '/deep/sign-in'
      path: '/deep/sign-in'
      fullPath: '/deep/sign-in'
      preLoaderRoute: typeof DeepDotsignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/settings'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexDotlazyRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AuthRouteChildren {
  AuthEmailCodeRoute: typeof AuthEmailCodeRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmailCodeRoute: AuthEmailCodeRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutDownloadRoute: typeof LayoutDownloadRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutPrivacyPolicyRoute: typeof LayoutPrivacyPolicyRoute
  LayoutReleasesRoute: typeof LayoutReleasesRoute
  LayoutTermsOfServiceRoute: typeof LayoutTermsOfServiceRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDownloadRoute: LayoutDownloadRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutPrivacyPolicyRoute: LayoutPrivacyPolicyRoute,
  LayoutReleasesRoute: LayoutReleasesRoute,
  LayoutTermsOfServiceRoute: LayoutTermsOfServiceRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AccountRouteChildren {
  AccountAiUsageDotlazyRoute: typeof AccountAiUsageDotlazyRoute
  AccountApiKeysDotlazyRoute: typeof AccountApiKeysDotlazyRoute
  AccountBillingDotlazyRoute: typeof AccountBillingDotlazyRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountSettingsIndexDotlazyRoute: typeof AccountSettingsIndexDotlazyRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAiUsageDotlazyRoute: AccountAiUsageDotlazyRoute,
  AccountApiKeysDotlazyRoute: AccountApiKeysDotlazyRoute,
  AccountBillingDotlazyRoute: AccountBillingDotlazyRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountSettingsIndexDotlazyRoute: AccountSettingsIndexDotlazyRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  OpenRoute: OpenRoute,
  DeepDotsignInRoute: DeepDotsignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
