import { ConnectionType } from '@tamery/shared/enums/connection-type'

import { formatSql } from '~/lib/formatter'

import type { Column } from '../../components/table/cell/utils'
import { buildWhere } from '../../queries/rows'
import { coldDialects } from '../../runtime/dialects'
import * as templates from '../templates'
import type { QueryParams, SchemaParams } from '../types'
import {
  filterExplicitIndexes,
  formatValue,
  getColumnType,
  groupIndexes,
  isSerialDefault,
  quoteIdentifier,
} from '../utils'

const inlineParameters = (
  sql: string,
  parameters: readonly unknown[]
): string => {
  let i = 0
  return sql.replaceAll(/\$\d+|@\d+|\?/gu, () => {
    i += 1
    return formatValue(parameters[i - 1])
  })
}

const qualify = (schema: string, table: string, dialect: ConnectionType) =>
  `${quoteIdentifier(schema, dialect)}.${quoteIdentifier(table, dialect)}`

export const generateQuerySQL = ({
  table,
  schema,
  filters,
  dialect = ConnectionType.Postgres,
}: QueryParams) => {
  const db = coldDialects[dialect]()
  const base = db
    .withSchema(schema)
    .$extendTables<{ [table]: Record<string, unknown> }>()
    .selectFrom(table)
    .selectAll()
  const query =
    filters.length > 0 ? base.where((eb) => buildWhere(eb, filters)) : base
  const compiled = query.compile()
  return formatSql(inlineParameters(compiled.sql, compiled.parameters), dialect)
}

const escapeSqlString = (s: string): string => s.replaceAll("'", "''")

const SERIAL_BY_INT_TYPE: Record<string, string> = {
  BIGINT: 'BIGSERIAL',
  INTEGER: 'SERIAL',
  SMALLINT: 'SMALLSERIAL',
}

const formatEnumType = (
  c: Column,
  enumName: string,
  values: string[],
  dialect: ConnectionType
) => {
  if (dialect === ConnectionType.MySQL) {
    const valuesList = values.map((v) => `'${escapeSqlString(v)}'`).join(', ')
    return `${c.type === 'set' ? 'SET' : 'ENUM'}(${valuesList})`
  }
  if (dialect === ConnectionType.MSSQL) {
    return enumName
  }
  return `"${enumName}"${c.isArray ? '[]' : ''}`
}

const formatScalarType = (c: Column, dialect: ConnectionType) => {
  const columnType =
    dialect === ConnectionType.ClickHouse ? c.type : (c.typeLabel ?? c.type)
  if (!columnType) {
    throw new Error(`Missing type for column ${c.id}`)
  }
  if (dialect === ConnectionType.ClickHouse) {
    return columnType
  }
  let typeDef = getColumnType(columnType, 'sql', dialect)

  if (typeof c.maxLength === 'number') {
    const len = c.maxLength === -1 ? 'MAX' : c.maxLength
    if (/(?:var)?char|binary/iu.test(typeDef) && !/text/iu.test(typeDef)) {
      typeDef += `(${len})`
    }
  }

  if (typeof c.precision === 'number' && /decimal|numeric/iu.test(typeDef)) {
    typeDef += `(${c.precision}${c.scale ? `, ${c.scale}` : ''})`
  }

  return typeDef.toUpperCase()
}

const getTypeDef = (
  c: Column,
  dialect: ConnectionType,
  usedEnums: Map<string, string[]>
): string => {
  if (
    dialect !== ConnectionType.ClickHouse &&
    c.enumName &&
    c.availableValues?.length
  ) {
    if (dialect === ConnectionType.Postgres) {
      usedEnums.set(c.enumName, c.availableValues)
    }
    return formatEnumType(c, c.enumName, c.availableValues, dialect)
  }

  return formatScalarType(c, dialect)
}

const buildColumnParts = (
  c: Column,
  typeDef: string,
  dialect: ConnectionType,
  pkColumns: string[],
  defaultValue?: string | null
): { parts: string[]; foreignKey: string | null } => {
  const quoted = quoteIdentifier(c.id, dialect)
  const parts = [quoted, typeDef]

  if (c.primaryKey) {
    pkColumns.push(quoted)
    if (dialect === ConnectionType.MySQL && /int|serial/iu.test(c.type ?? '')) {
      parts.push('AUTO_INCREMENT')
    }
  }

  if (c.isIdentity && dialect === ConnectionType.MSSQL) {
    parts.push('IDENTITY(1,1)')
  }
  if (c.isIdentity && dialect === ConnectionType.Postgres) {
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  }

  if (defaultValue !== undefined && defaultValue !== null) {
    parts.push(`DEFAULT ${defaultValue}`)
  }

  if (!c.isNullable) {
    parts.push('NOT NULL')
  }

  if (c.unique && !c.primaryKey && dialect !== ConnectionType.ClickHouse) {
    parts.push('UNIQUE')
  }

  let foreignKey: string | null = null
  if (c.foreign && dialect !== ConnectionType.ClickHouse) {
    const ref = qualify(c.foreign.schema, c.foreign.table, dialect)
    const col = quoteIdentifier(c.foreign.column, dialect)
    let fk = `  FOREIGN KEY (${quoted}) REFERENCES ${ref}(${col})`

    if (c.foreign.onDelete) {
      fk += ` ON DELETE ${c.foreign.onDelete}`
    }
    if (c.foreign.onUpdate) {
      fk += ` ON UPDATE ${c.foreign.onUpdate}`
    }

    foreignKey = fk
  }

  return { foreignKey, parts }
}

const buildPostgresEnumStatements = (
  usedEnums: Map<string, string[]>
): string[] =>
  Array.from(usedEnums.entries(), ([name, values]) => {
    const vals = values.map((v) => `'${escapeSqlString(v)}'`).join(', ')
    return `CREATE TYPE "${name}" AS ENUM (${vals});`
  })

const appendIndexStatements = (
  statement: string,
  qualifiedTable: string,
  columns: Column[],
  groupedIndexes: ReturnType<typeof groupIndexes>,
  dialect: ConnectionType
): string => {
  const explicit = filterExplicitIndexes(groupedIndexes, columns)
  if (explicit.length === 0) {
    return statement
  }

  const lines = explicit.map((idx) =>
    [
      'CREATE',
      idx.isUnique ? 'UNIQUE' : '',
      'INDEX',
      `${quoteIdentifier(idx.name, dialect)}`,
      'ON',
      qualifiedTable,
      dialect === ConnectionType.Postgres && idx.type
        ? `USING ${idx.type}`
        : '',
      `(${[
        ...idx.columns.map((c) => quoteIdentifier(c, dialect)),
        ...idx.customExpressions,
      ].join(', ')})`,
    ]
      .filter(Boolean)
      .join(' ')
  )
  return `${statement}\n\n${lines.join('\n')}`
}

export const generateSchemaSQL = ({
  table,
  schema,
  columns,
  dialect,
  indexes = [],
}: SchemaParams) => {
  const usedEnums = new Map<string, string[]>()
  const pkColumns: string[] = []
  const columnLines: string[] = []
  const foreignKeys: string[] = []

  for (const c of columns) {
    let typeDef = getTypeDef(c, dialect, usedEnums)
    let { defaultValue } = c

    if (dialect === ConnectionType.Postgres && isSerialDefault(defaultValue)) {
      const serialType = SERIAL_BY_INT_TYPE[typeDef]
      if (serialType) {
        typeDef = serialType
        defaultValue = null
      }
    }

    const { parts, foreignKey } = buildColumnParts(
      c,
      typeDef,
      dialect,
      pkColumns,
      defaultValue
    )
    columnLines.push(`  ${parts.join(' ')}`)
    if (foreignKey) {
      foreignKeys.push(foreignKey)
    }
  }

  const constraints = [...foreignKeys]
  if (pkColumns.length > 0 && dialect !== ConnectionType.ClickHouse) {
    constraints.unshift(`  PRIMARY KEY (${pkColumns.join(', ')})`)
  }

  const qualifiedTable = qualify(schema, table, dialect)
  let statement = templates.sqlSchemaTemplate(
    qualifiedTable,
    [...columnLines, ...constraints].join(',\n')
  )

  if (dialect === ConnectionType.ClickHouse) {
    const orderBy =
      pkColumns.length > 0 ? `(${pkColumns.join(', ')})` : 'tuple()'
    return statement.replace(
      /\);\s*$/u,
      `) ENGINE = MergeTree() ORDER BY ${orderBy};`
    )
  }

  statement = appendIndexStatements(
    statement,
    qualifiedTable,
    columns,
    groupIndexes(indexes, schema, table),
    dialect
  )

  const enumStatements =
    usedEnums.size > 0
      ? `${buildPostgresEnumStatements(usedEnums).join('\n')}\n\n`
      : ''

  return `${enumStatements}${statement}`
}
