import { describe, expect, it, mock } from 'bun:test'

import { ConnectionType } from '@tamery/shared/enums/connection-type'

import type { Column } from '../../components/table/cell/utils'
import { generateQueryKysely } from './kysely'
import { generateSchemaPrisma } from './prisma'
import { generateSchemaTypeScript } from './typescript'

mock.module('../../queries/rows', () => ({ buildWhere: () => null }))
mock.module('../../runtime/dialects', () => ({ coldDialects: {} }))
const { generateSchemaSQL } = await import('./sql')

const columns: Column[] = [
  {
    defaultValue: null,
    id: 'id',
    isIdentity: true,
    isNullable: false,
    primaryKey: 'pk',
    type: 'integer',
    typeLabel: 'integer',
    uiType: 'raw',
  },
  {
    defaultValue: 'now()',
    id: 'created_at',
    isNullable: false,
    type: 'timestamp with time zone',
    typeLabel: 'timestamptz',
    uiType: 'datetime',
  },
  {
    defaultValue: null,
    foreign: { column: 'id', name: 'fk', schema: 'auth', table: 'users' },
    id: 'user_id',
    isNullable: true,
    type: 'uuid',
    typeLabel: 'uuid',
    uiType: 'raw',
  },
  {
    defaultValue: null,
    id: 'tags',
    isArray: true,
    isNullable: true,
    type: 'text[]',
    typeLabel: 'text[]',
    uiType: 'list',
  },
  {
    defaultValue: null,
    id: 'duration',
    isNullable: true,
    type: 'interval',
    typeLabel: 'interval',
    uiType: 'raw',
  },
]

describe('generators (postgres)', () => {
  it('qualifies schema, keeps identity, resolves FK schema', () => {
    const sql = generateSchemaSQL({
      columns,
      dialect: ConnectionType.Postgres,
      schema: 'app',
      table: 'events',
    })
    expect(sql).toContain('CREATE TABLE "app"."events"')
    expect(sql).toContain('GENERATED BY DEFAULT AS IDENTITY')
    expect(sql).toContain('"created_at" TIMESTAMPTZ DEFAULT now() NOT NULL')
    expect(sql).toContain('"tags" TEXT[]')
    expect(sql).toContain('REFERENCES "auth"."users"("id")')
  })

  it('maps arrays and does not confuse interval with int', () => {
    const ts = generateSchemaTypeScript({
      columns,
      dialect: ConnectionType.Postgres,
      schema: 'app',
      table: 'events',
    })
    expect(ts).toContain('tags?: string[] | null;')
    expect(ts).toContain('duration?: string | null;')
  })

  it('prisma emits defaults, uuid and lists', () => {
    const prisma = generateSchemaPrisma({
      columns,
      dialect: ConnectionType.Postgres,
      schema: 'app',
      table: 'events',
    })
    expect(prisma).toContain('@id @default(autoincrement())')
    expect(prisma).toContain('@default(now())')
    expect(prisma).toContain('@db.Uuid')
    expect(prisma).toContain('tags      String[]')
  })

  it('kysely null checks compile to (column, is, null)', () => {
    const query = generateQueryKysely({
      filters: [
        {
          column: 'user_id',
          ref: { hasValue: false, label: 'Is null', operator: 'IS NULL' },
          values: [],
        },
        {
          column: 'id',
          ref: { isArray: true, label: 'In', operator: 'IN' },
          values: [1, 2],
        },
      ],
      schema: 'app',
      table: 'events',
    })
    expect(query).toContain(".where('user_id', 'is', null)")
    expect(query).toContain(".where('id', 'in', [1,2])")
  })
})
