/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenRouteImport } from './routes/open'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDownloadRouteImport } from './routes/_layout/download'

const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDownloadRoute = LayoutDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/open': typeof OpenRoute
  '/download': typeof LayoutDownloadRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/open': typeof OpenRoute
  '/download': typeof LayoutDownloadRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/open': typeof OpenRoute
  '/_layout/download': typeof LayoutDownloadRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/open' | '/download' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/open' | '/download' | '/'
  id: '__root__' | '/_layout' | '/open' | '/_layout/download' | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  OpenRoute: typeof OpenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/download': {
      id: '/_layout/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof LayoutDownloadRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDownloadRoute: typeof LayoutDownloadRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDownloadRoute: LayoutDownloadRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  OpenRoute: OpenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
