/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenRouteImport } from './routes/open'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as DeepSignInRouteImport } from './routes/deep.sign-in'
import { Route as LayoutReleasesRouteImport } from './routes/_layout/releases'
import { Route as LayoutHomeRouteImport } from './routes/_layout/home'
import { Route as LayoutDownloadRouteImport } from './routes/_layout/download'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'

const AccountSettingsLazyRouteImport = createFileRoute('/account/settings')()
const AccountBillingLazyRouteImport = createFileRoute('/account/billing')()
const LayoutTermsOfServiceLazyRouteImport = createFileRoute(
  '/_layout/terms-of-service',
)()
const LayoutPrivacyPolicyLazyRouteImport = createFileRoute(
  '/_layout/privacy-policy',
)()
const AuthForgotPasswordLazyRouteImport = createFileRoute(
  '/_auth/forgot-password',
)()

const OpenRoute = OpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AccountSettingsLazyRoute = AccountSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./routes/account/settings.lazy').then((d) => d.Route),
)
const AccountBillingLazyRoute = AccountBillingLazyRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./routes/account/billing.lazy').then((d) => d.Route),
)
const LayoutTermsOfServiceLazyRoute =
  LayoutTermsOfServiceLazyRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/terms-of-service.lazy').then((d) => d.Route),
  )
const LayoutPrivacyPolicyLazyRoute = LayoutPrivacyPolicyLazyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/privacy-policy.lazy').then((d) => d.Route),
)
const AuthForgotPasswordLazyRoute = AuthForgotPasswordLazyRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/forgot-password.lazy').then((d) => d.Route),
)
const DeepSignInRoute = DeepSignInRouteImport.update({
  id: '/deep/sign-in',
  path: '/deep/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutReleasesRoute = LayoutReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDownloadRoute = LayoutDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/open': typeof OpenRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/download': typeof LayoutDownloadRoute
  '/home': typeof LayoutHomeRoute
  '/releases': typeof LayoutReleasesRoute
  '/deep/sign-in': typeof DeepSignInRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyLazyRoute
  '/terms-of-service': typeof LayoutTermsOfServiceLazyRoute
  '/account/billing': typeof AccountBillingLazyRoute
  '/account/settings': typeof AccountSettingsLazyRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/open': typeof OpenRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/download': typeof LayoutDownloadRoute
  '/home': typeof LayoutHomeRoute
  '/releases': typeof LayoutReleasesRoute
  '/deep/sign-in': typeof DeepSignInRoute
  '/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyLazyRoute
  '/terms-of-service': typeof LayoutTermsOfServiceLazyRoute
  '/account/billing': typeof AccountBillingLazyRoute
  '/account/settings': typeof AccountSettingsLazyRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/open': typeof OpenRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_layout/download': typeof LayoutDownloadRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/releases': typeof LayoutReleasesRoute
  '/deep/sign-in': typeof DeepSignInRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordLazyRoute
  '/_layout/privacy-policy': typeof LayoutPrivacyPolicyLazyRoute
  '/_layout/terms-of-service': typeof LayoutTermsOfServiceLazyRoute
  '/account/billing': typeof AccountBillingLazyRoute
  '/account/settings': typeof AccountSettingsLazyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/open'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/download'
    | '/home'
    | '/releases'
    | '/deep/sign-in'
    | '/forgot-password'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/account/billing'
    | '/account/settings'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/open'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/download'
    | '/home'
    | '/releases'
    | '/deep/sign-in'
    | '/forgot-password'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/account/billing'
    | '/account/settings'
    | '/account'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/account'
    | '/open'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_layout/download'
    | '/_layout/home'
    | '/_layout/releases'
    | '/deep/sign-in'
    | '/_auth/forgot-password'
    | '/_layout/privacy-policy'
    | '/_layout/terms-of-service'
    | '/account/billing'
    | '/account/settings'
    | '/_layout/'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  OpenRoute: typeof OpenRoute
  DeepSignInRoute: typeof DeepSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsLazyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingLazyRouteImport
      parentRoute: typeof AccountRoute
    }
    '/_layout/terms-of-service': {
      id: '/_layout/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LayoutTermsOfServiceLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy-policy': {
      id: '/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPrivacyPolicyLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/deep/sign-in': {
      id: '/deep/sign-in'
      path: '/deep/sign-in'
      fullPath: '/deep/sign-in'
      preLoaderRoute: typeof DeepSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/releases': {
      id: '/_layout/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof LayoutReleasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/download': {
      id: '/_layout/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof LayoutDownloadRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthForgotPasswordLazyRoute: typeof AuthForgotPasswordLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthForgotPasswordLazyRoute: AuthForgotPasswordLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutDownloadRoute: typeof LayoutDownloadRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutReleasesRoute: typeof LayoutReleasesRoute
  LayoutPrivacyPolicyLazyRoute: typeof LayoutPrivacyPolicyLazyRoute
  LayoutTermsOfServiceLazyRoute: typeof LayoutTermsOfServiceLazyRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDownloadRoute: LayoutDownloadRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutReleasesRoute: LayoutReleasesRoute,
  LayoutPrivacyPolicyLazyRoute: LayoutPrivacyPolicyLazyRoute,
  LayoutTermsOfServiceLazyRoute: LayoutTermsOfServiceLazyRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AccountRouteChildren {
  AccountBillingLazyRoute: typeof AccountBillingLazyRoute
  AccountSettingsLazyRoute: typeof AccountSettingsLazyRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBillingLazyRoute: AccountBillingLazyRoute,
  AccountSettingsLazyRoute: AccountSettingsLazyRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  OpenRoute: OpenRoute,
  DeepSignInRoute: DeepSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
