import { ConnectionType } from '@tamery/shared/enums/connection-type'
import { toKyselyFilter } from '@tamery/shared/filters'

import { explicitIndexes } from '~/core/codegen/indexes'
import type { QueryParams, SchemaParams } from '~/core/codegen/types'
import {
  formatValue,
  isSerialDefault,
  isSingleColumnConstraint,
  quoteIdentifier,
} from '~/core/codegen/utils'
import { coldDialects } from '~/core/runtime/dialects'
import type { Column } from '~/core/table/cell/utils'
import { formatSql } from '~/utils/formatter'

export const inlineParameters = (
  sql: string,
  parameters: readonly unknown[],
  dialect: ConnectionType
): string => {
  let next = 0
  return sql.replaceAll(
    /"(?:[^"]|"")*"|`(?:[^`]|``)*`|\[(?:[^\]]|\]\])*\]|'(?:[^']|'')*'|[$@](?<index>\d+)|\?/gu,
    (token, ...args) => {
      if (!/^[$@?]/u.test(token)) {
        return token
      }
      const index = args.at(-1)?.index
      next += 1
      return formatValue(
        parameters[index ? Number(index) - 1 : next - 1],
        dialect
      )
    }
  )
}

const qualify = (schema: string, table: string, dialect: ConnectionType) =>
  `${quoteIdentifier(schema, dialect)}.${quoteIdentifier(table, dialect)}`

export const generateQuerySQL = ({
  table,
  schema,
  filters,
  dialect,
}: QueryParams) => {
  const db = coldDialects[dialect]()
  const base = db
    .withSchema(schema)
    .$extendTables<{ [table]: Record<string, unknown> }>()
    .selectFrom(table)
    .selectAll()
  const query =
    filters.length > 0 ? base.where((eb) => toKyselyFilter(eb, filters)) : base
  const compiled = query.compile()
  return formatSql(
    inlineParameters(compiled.sql, compiled.parameters, dialect),
    dialect
  )
}

const SERIAL_BY_INT_TYPE: Record<string, string> = {
  BIGINT: 'BIGSERIAL',
  INTEGER: 'SERIAL',
  SMALLINT: 'SMALLSERIAL',
}

const formatEnumType = (
  c: Column,
  enumName: string,
  values: string[],
  dialect: ConnectionType
) => {
  if (dialect === ConnectionType.MySQL) {
    const valuesList = values.map((v) => formatValue(v, dialect)).join(', ')
    return `${c.type === 'set' ? 'SET' : 'ENUM'}(${valuesList})`
  }
  if (dialect === ConnectionType.MSSQL) {
    return enumName
  }
  return `"${enumName}"${c.isArray ? '[]' : ''}`
}

const formatScalarType = (c: Column, dialect: ConnectionType) => {
  let typeDef =
    dialect === ConnectionType.ClickHouse ? c.type : (c.typeLabel ?? c.type)
  if (!typeDef) {
    throw new Error(`Missing type for column ${c.id}`)
  }
  if (dialect === ConnectionType.ClickHouse) {
    return typeDef
  }
  if (dialect !== ConnectionType.Postgres && c.declaredType) {
    return c.declaredType.replace(/^[^']*/u, (head) => head.toUpperCase())
  }

  if (typeof c.maxLength === 'number') {
    const len = c.maxLength === -1 ? 'MAX' : c.maxLength
    if (/(?:var)?char|binary/iu.test(typeDef) && !/text/iu.test(typeDef)) {
      typeDef += `(${len})`
    }
  }

  if (typeof c.precision === 'number' && /decimal|numeric/iu.test(typeDef)) {
    typeDef += `(${c.precision}${c.scale ? `, ${c.scale}` : ''})`
  }

  return typeDef.toUpperCase()
}

const getTypeDef = (
  c: Column,
  dialect: ConnectionType,
  usedEnums: Map<string, string[]>
): string => {
  if (
    dialect !== ConnectionType.ClickHouse &&
    c.enumName &&
    c.availableValues?.length
  ) {
    if (dialect === ConnectionType.Postgres) {
      usedEnums.set(c.enumName, c.availableValues)
    }
    return formatEnumType(c, c.enumName, c.availableValues, dialect)
  }

  return formatScalarType(c, dialect)
}

const buildColumnParts = (
  c: Column,
  typeDef: string,
  dialect: ConnectionType,
  pkColumns: string[],
  unique: boolean,
  defaultValue?: string | null
): { parts: string[]; foreignKey: string | null } => {
  const quoted = quoteIdentifier(c.id, dialect)
  const parts = [quoted, typeDef]

  if (c.primaryKey) {
    pkColumns.push(quoted)
  }

  if (c.isIdentity && dialect === ConnectionType.MySQL) {
    parts.push('AUTO_INCREMENT')
  }
  if (c.isIdentity && dialect === ConnectionType.MSSQL) {
    parts.push('IDENTITY(1,1)')
  }
  if (c.isIdentity && dialect === ConnectionType.Postgres) {
    parts.push('GENERATED BY DEFAULT AS IDENTITY')
  }

  if (defaultValue !== undefined && defaultValue !== null) {
    parts.push(`DEFAULT ${defaultValue}`)
  }

  if (!c.isNullable) {
    parts.push('NOT NULL')
  }

  if (unique && !c.primaryKey && dialect !== ConnectionType.ClickHouse) {
    parts.push('UNIQUE')
  }

  let foreignKey: string | null = null
  if (c.foreign && dialect !== ConnectionType.ClickHouse) {
    const ref = qualify(c.foreign.schema, c.foreign.table, dialect)
    const col = quoteIdentifier(c.foreign.column, dialect)
    let fk = `  FOREIGN KEY (${quoted}) REFERENCES ${ref}(${col})`

    if (c.foreign.onDelete) {
      fk += ` ON DELETE ${c.foreign.onDelete}`
    }
    if (c.foreign.onUpdate) {
      fk += ` ON UPDATE ${c.foreign.onUpdate}`
    }

    foreignKey = fk
  }

  return { foreignKey, parts }
}

const indexStatement = (
  idx: ReturnType<typeof explicitIndexes>[number],
  qualifiedTable: string,
  dialect: ConnectionType
) =>
  idx.custom && idx.definition
    ? idx.definition
    : [
        'CREATE',
        idx.isUnique ? 'UNIQUE' : '',
        'INDEX',
        quoteIdentifier(idx.name, dialect),
        'ON',
        qualifiedTable,
        dialect === ConnectionType.Postgres && idx.type
          ? `USING ${idx.type}`
          : '',
        `(${idx.keys
          .map((key) =>
            'column' in key
              ? quoteIdentifier(key.column, dialect)
              : key.expression
          )
          .join(', ')})`,
      ]
        .filter(Boolean)
        .join(' ')

export const generateSchemaSQL = ({
  table,
  schema,
  columns,
  dialect,
  indexes,
}: SchemaParams) => {
  const usedEnums = new Map<string, string[]>()
  const pkColumns: string[] = []
  const columnLines: string[] = []
  const foreignKeys: string[] = []

  for (const c of columns) {
    let typeDef = getTypeDef(c, dialect, usedEnums)
    let { defaultValue } = c

    if (dialect === ConnectionType.Postgres && isSerialDefault(defaultValue)) {
      const serialType = SERIAL_BY_INT_TYPE[typeDef]
      if (serialType) {
        typeDef = serialType
        defaultValue = null
      }
    }

    const { parts, foreignKey } = buildColumnParts(
      c,
      typeDef,
      dialect,
      pkColumns,
      isSingleColumnConstraint(c, columns, 'unique'),
      defaultValue
    )
    columnLines.push(`  ${parts.join(' ')}`)
    if (foreignKey) {
      foreignKeys.push(foreignKey)
    }
  }

  const primaryKey =
    pkColumns.length > 0 && dialect !== ConnectionType.ClickHouse
      ? [`  PRIMARY KEY (${pkColumns.join(', ')})`]
      : []
  const qualifiedTable = qualify(schema, table, dialect)
  const createTable = `CREATE TABLE ${qualifiedTable} (\n${[...columnLines, ...primaryKey, ...foreignKeys].join(',\n')}\n)`

  if (dialect === ConnectionType.ClickHouse) {
    const orderBy =
      pkColumns.length > 0 ? `(${pkColumns.join(', ')})` : 'tuple()'
    return `${createTable} ENGINE = MergeTree() ORDER BY ${orderBy};`
  }

  const enumStatements = Array.from(
    usedEnums,
    ([name, values]) =>
      `CREATE TYPE "${name}" AS ENUM (${values.map((v) => formatValue(v, dialect)).join(', ')});`
  )
  const indexStatements = explicitIndexes({
    columns,
    indexes,
    schema,
    table,
  }).map((idx) => `${indexStatement(idx, qualifiedTable, dialect)};`)

  return [
    enumStatements.join('\n'),
    `${createTable};`,
    indexStatements.join('\n'),
  ]
    .filter(Boolean)
    .join('\n\n')
}
