import { ConnectionType } from '@tamery/shared/enums/connection-type'

const COMMON_KEYWORDS = [
  'ADD',
  'ALL',
  'ALTER',
  'AND',
  'ANY',
  'AS',
  'ASC',
  'BEGIN',
  'BETWEEN',
  'BY',
  'CASCADE',
  'CASE',
  'CAST',
  'CHECK',
  'COLUMN',
  'COMMIT',
  'CONSTRAINT',
  'CREATE',
  'CROSS',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'CURRENT_USER',
  'DATABASE',
  'DEFAULT',
  'DELETE',
  'DESC',
  'DISTINCT',
  'DROP',
  'ELSE',
  'END',
  'EXCEPT',
  'EXISTS',
  'EXPLAIN',
  'FALSE',
  'FETCH',
  'FIRST',
  'FOREIGN',
  'FROM',
  'FULL',
  'GROUP',
  'HAVING',
  'IF',
  'IN',
  'INDEX',
  'INNER',
  'INSERT',
  'INTERSECT',
  'INTO',
  'IS',
  'JOIN',
  'KEY',
  'LAST',
  'LEFT',
  'LIKE',
  'LIMIT',
  'NATURAL',
  'NOT',
  'NULL',
  'NULLS',
  'OFFSET',
  'ON',
  'OR',
  'ORDER',
  'OUTER',
  'PRIMARY',
  'REFERENCES',
  'RIGHT',
  'ROLLBACK',
  'ROW',
  'ROWS',
  'SCHEMA',
  'SELECT',
  'SET',
  'SHOW',
  'START',
  'TABLE',
  'THEN',
  'TO',
  'TRANSACTION',
  'TRUE',
  'TRUNCATE',
  'UNION',
  'UNIQUE',
  'UPDATE',
  'USING',
  'VALUES',
  'VIEW',
  'WHEN',
  'WHERE',
  'WITH',
]

const COMMON_FUNCTIONS = [
  'ABS',
  'AVG',
  'CEIL',
  'COALESCE',
  'CONCAT',
  'COUNT',
  'FLOOR',
  'GREATEST',
  'LEAST',
  'LENGTH',
  'LOWER',
  'MAX',
  'MIN',
  'NOW',
  'NULLIF',
  'POWER',
  'REPLACE',
  'ROUND',
  'SUBSTRING',
  'SUM',
  'TRIM',
  'UPPER',
]

const COMMON_TYPES = [
  'BIGINT',
  'BOOLEAN',
  'CHAR',
  'DATE',
  'DECIMAL',
  'DOUBLE',
  'FLOAT',
  'INT',
  'INTEGER',
  'JSON',
  'NUMERIC',
  'SMALLINT',
  'TEXT',
  'TIME',
  'TIMESTAMP',
  'VARCHAR',
]

export interface DialectSpec {
  identifierQuotes: readonly string[]
  dollarQuotes: boolean
  /** Backslash escapes inside `'...'` (MySQL/ClickHouse); Postgres and SQL Server only double the quote. */
  backslashEscapes: boolean
  hashComments: boolean
  atVariables: boolean
  goBatches: boolean
  /** `BEGIN … COMMIT` really runs as a transaction; ClickHouse's driver only fakes commit and rollback. */
  transactions: boolean
  functions: ReadonlySet<string>
  keywords: ReadonlySet<string>
  types: ReadonlySet<string>
}

const spec = (
  overrides: Partial<Omit<DialectSpec, 'functions' | 'keywords' | 'types'>> & {
    functions?: string[]
    keywords?: string[]
    types?: string[]
  }
): DialectSpec => ({
  atVariables: false,
  backslashEscapes: false,
  dollarQuotes: false,
  goBatches: false,
  hashComments: false,
  identifierQuotes: ['"'],
  transactions: true,
  ...overrides,
  functions: new Set([...COMMON_FUNCTIONS, ...(overrides.functions ?? [])]),
  keywords: new Set([...COMMON_KEYWORDS, ...(overrides.keywords ?? [])]),
  types: new Set([...COMMON_TYPES, ...(overrides.types ?? [])]),
})

export const dialects: Record<ConnectionType, DialectSpec> = {
  [ConnectionType.ClickHouse]: spec({
    backslashEscapes: true,
    functions: [
      'ARRAYJOIN',
      'COUNTIF',
      'FORMATDATETIME',
      'GROUPARRAY',
      'SUMIF',
      'TODATE',
      'TODATETIME',
      'TOSTRING',
      'UNIQ',
      'UNIQEXACT',
    ],
    hashComments: true,
    identifierQuotes: ['"', '`'],
    keywords: [
      'ARRAY',
      'ATTACH',
      'CLUSTER',
      'DETACH',
      'DICTIONARY',
      'ENGINE',
      'FINAL',
      'FORMAT',
      'MATERIALIZED',
      'OPTIMIZE',
      'PARTITION',
      'PREWHERE',
      'SAMPLE',
      'SETTINGS',
      'SYSTEM',
      'TTL',
    ],
    transactions: false,
    types: [
      'DATETIME',
      'DATETIME64',
      'FLOAT32',
      'FLOAT64',
      'INT16',
      'INT32',
      'INT64',
      'INT8',
      'STRING',
      'UINT16',
      'UINT32',
      'UINT64',
      'UINT8',
      'UUID',
    ],
  }),
  [ConnectionType.MSSQL]: spec({
    atVariables: true,
    functions: [
      'CHARINDEX',
      'CONVERT',
      'DATEADD',
      'DATEDIFF',
      'GETDATE',
      'ISNULL',
      'LEN',
      'NEWID',
      'OBJECT_ID',
      'STRING_AGG',
      'SYSDATETIME',
    ],
    goBatches: true,
    identifierQuotes: ['"', '['],
    keywords: [
      'APPLY',
      'CATCH',
      'DECLARE',
      'EXEC',
      'EXECUTE',
      'GO',
      'IDENTITY',
      'MERGE',
      'NOLOCK',
      'OUTPUT',
      'OVER',
      'PIVOT',
      'PRINT',
      'PROCEDURE',
      'RAISERROR',
      'THROW',
      'TOP',
      'TRAN',
      'TRY',
      'UNPIVOT',
      'WHILE',
    ],
    types: [
      'BIT',
      'DATETIME',
      'DATETIME2',
      'MONEY',
      'NVARCHAR',
      'UNIQUEIDENTIFIER',
    ],
  }),
  [ConnectionType.MySQL]: spec({
    atVariables: true,
    backslashEscapes: true,
    functions: [
      'DATE_FORMAT',
      'GROUP_CONCAT',
      'IFNULL',
      'JSON_EXTRACT',
      'LAST_INSERT_ID',
      'RAND',
      'UUID',
    ],
    hashComments: true,
    identifierQuotes: ['`'],
    keywords: [
      'AUTO_INCREMENT',
      'CHARSET',
      'COLLATE',
      'DUPLICATE',
      'ENGINE',
      'IGNORE',
      'LOCK',
      'PROCEDURE',
      'REGEXP',
      'RENAME',
      'STRAIGHT_JOIN',
      'UNLOCK',
      'UNSIGNED',
      'USE',
    ],
    types: ['DATETIME', 'ENUM', 'LONGTEXT', 'MEDIUMINT', 'TINYINT'],
  }),
  [ConnectionType.Postgres]: spec({
    dollarQuotes: true,
    functions: [
      'ARRAY_AGG',
      'DATE_TRUNC',
      'EXTRACT',
      'GEN_RANDOM_UUID',
      'GENERATE_SERIES',
      'JSONB_AGG',
      'JSONB_BUILD_OBJECT',
      'ROW_NUMBER',
      'STRING_AGG',
      'TO_CHAR',
      'UNNEST',
    ],
    keywords: [
      'ANALYZE',
      'ARRAY',
      'CONFLICT',
      'DO',
      'FILTER',
      'FUNCTION',
      'ILIKE',
      'LATERAL',
      'MATERIALIZED',
      'NOTHING',
      'ONLY',
      'OVER',
      'PARTITION',
      'RETURNING',
      'RETURNS',
      'SIMILAR',
      'VACUUM',
      'WINDOW',
    ],
    types: ['BYTEA', 'INTERVAL', 'JSONB', 'SERIAL', 'TIMESTAMPTZ', 'UUID'],
  }),
}
