import type { Metadata } from 'next'
import { MuseoModerno, Nunito_Sans } from 'next/font/google'
import './globals.css'

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
})

const museoModerno = MuseoModerno({
  variable: '--font-museo-moderno',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${nunitoSans.variable} ${museoModerno.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
