import { Button } from '@tamery/ui/components/button'
import { LoadingContent } from '@tamery/ui/components/custom/loading-content'
import { Field, FieldLabel } from '@tamery/ui/components/field'
import { useAppForm } from '@tamery/ui/components/tanstack-form'
import { useStore } from '@tanstack/react-form'
import { createLazyFileRoute, useRouter } from '@tanstack/react-router'
import { type } from 'arktype'

import { authClient } from '~/lib/auth'
import { handleError } from '~/utils/error'

export const Route = createLazyFileRoute('/_auth/forgot-password')({
  component: ForgotPasswordPage,
})

const emailSchema = type({
  email: type('string.email').configure({ message: 'Invalid email address' }),
})

function ForgotPasswordPage() {
  const router = useRouter()
  // Token will be generated by auth client
  const href = router.buildLocation({ to: '/reset-password', search: { token: '' } }).href

  const form = useAppForm({
    defaultValues: {
      email: '',
    } satisfies typeof emailSchema.infer,
    validators: {
      onSubmit: emailSchema,
    },
    onSubmit: async ({ value }) => {
      const { error } = await authClient.requestPasswordReset({
        email: value.email,
        redirectTo: location.origin + href,
      })

      if (error) {
        handleError(error)
      }
    },
  })

  const isSubmitting = useStore(form.store, state => state.isSubmitting)

  if (isSubmitting) {
    return (
      <div className="flex flex-col justify-center gap-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">Email sent successfully</h2>
          <p className="max-w-sm text-sm text-muted-foreground">
            We've sent you an email with a link to reset your password. Click the link and create a
            new password.
          </p>
        </div>
      </div>
    )
  }

  return (
    <>
      <div className="space-y-2">
        <h1
          className={`
          flex items-center gap-2 text-2xl font-semibold tracking-tight
        `}
        >
          Forgot your password?
        </h1>
        <p className="text-sm text-muted-foreground">
          Enter your email address and we'll send you a reset link to reset your password.
        </p>
      </div>
      <form
        className="space-y-4"
        onSubmit={e => {
          e.preventDefault()
          form.handleSubmit()
        }}
      >
        <form.AppField name="email">
          {field => (
            <Field>
              <FieldLabel>Email</FieldLabel>
              <field.Input
                placeholder="example@gmail.com"
                type="email"
                autoCapitalize="none"
                autoComplete="email"
                spellCheck={false}
                autoFocus
              />
              <field.Error />
            </Field>
          )}
        </form.AppField>
        <Button className="w-full" type="submit" disabled={isSubmitting}>
          <LoadingContent loading={isSubmitting}>Send reset link</LoadingContent>
        </Button>
      </form>
    </>
  )
}
