/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicAuthImport } from './routes/(public)/_auth'
import { Route as protectedDashboardImport } from './routes/(protected)/_dashboard'
import { Route as protectedDashboardIndexImport } from './routes/(protected)/_dashboard/index'
import { Route as publicAuthTwoFactorImport } from './routes/(public)/_auth/two-factor'
import { Route as publicAuthSignUpImport } from './routes/(public)/_auth/sign-up'
import { Route as publicAuthSignInImport } from './routes/(public)/_auth/sign-in'
import { Route as protectedDashboardDatabasesIndexImport } from './routes/(protected)/_dashboard/databases/index'
import { Route as publicAuthTwoFactorSetupImport } from './routes/(public)/_auth/two-factor.setup'
import { Route as protectedDashboardDatabasesIdImport } from './routes/(protected)/_dashboard/databases/$id'

// Create Virtual Routes

const publicImport = createFileRoute('/(public)')()
const protectedImport = createFileRoute('/(protected)')()

// Create/Update Routes

const publicRoute = publicImport.update({
  id: '/(public)',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const protectedRoute = protectedImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRoute,
} as any)

const publicAuthRoute = publicAuthImport.update({
  id: '/_auth',
  getParentRoute: () => publicRoute,
} as any)

const protectedDashboardRoute = protectedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => protectedRoute,
} as any)

const protectedDashboardIndexRoute = protectedDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDashboardRoute,
} as any)

const publicAuthTwoFactorRoute = publicAuthTwoFactorImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => publicAuthRoute,
} as any)

const publicAuthSignUpRoute = publicAuthSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicAuthRoute,
} as any)

const publicAuthSignInRoute = publicAuthSignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicAuthRoute,
} as any)

const protectedDashboardDatabasesIndexRoute =
  protectedDashboardDatabasesIndexImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => protectedDashboardRoute,
  } as any)

const publicAuthTwoFactorSetupRoute = publicAuthTwoFactorSetupImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => publicAuthTwoFactorRoute,
} as any)

const protectedDashboardDatabasesIdRoute =
  protectedDashboardDatabasesIdImport.update({
    id: '/databases/$id',
    path: '/databases/$id',
    getParentRoute: () => protectedDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/_dashboard': {
      id: '/(protected)/_dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedDashboardImport
      parentRoute: typeof protectedRoute
    }
    '/(public)': {
      id: '/(public)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicImport
      parentRoute: typeof rootRoute
    }
    '/(public)/_auth': {
      id: '/(public)/_auth'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicAuthImport
      parentRoute: typeof publicRoute
    }
    '/(public)/_auth/sign-in': {
      id: '/(public)/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicAuthSignInImport
      parentRoute: typeof publicAuthImport
    }
    '/(public)/_auth/sign-up': {
      id: '/(public)/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicAuthSignUpImport
      parentRoute: typeof publicAuthImport
    }
    '/(public)/_auth/two-factor': {
      id: '/(public)/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof publicAuthTwoFactorImport
      parentRoute: typeof publicAuthImport
    }
    '/(protected)/_dashboard/': {
      id: '/(protected)/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedDashboardIndexImport
      parentRoute: typeof protectedDashboardImport
    }
    '/(protected)/_dashboard/databases/$id': {
      id: '/(protected)/_dashboard/databases/$id'
      path: '/databases/$id'
      fullPath: '/databases/$id'
      preLoaderRoute: typeof protectedDashboardDatabasesIdImport
      parentRoute: typeof protectedDashboardImport
    }
    '/(public)/_auth/two-factor/setup': {
      id: '/(public)/_auth/two-factor/setup'
      path: '/setup'
      fullPath: '/two-factor/setup'
      preLoaderRoute: typeof publicAuthTwoFactorSetupImport
      parentRoute: typeof publicAuthTwoFactorImport
    }
    '/(protected)/_dashboard/databases/': {
      id: '/(protected)/_dashboard/databases/'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof protectedDashboardDatabasesIndexImport
      parentRoute: typeof protectedDashboardImport
    }
  }
}

// Create and export the route tree

interface protectedDashboardRouteChildren {
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
  protectedDashboardDatabasesIdRoute: typeof protectedDashboardDatabasesIdRoute
  protectedDashboardDatabasesIndexRoute: typeof protectedDashboardDatabasesIndexRoute
}

const protectedDashboardRouteChildren: protectedDashboardRouteChildren = {
  protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  protectedDashboardDatabasesIdRoute: protectedDashboardDatabasesIdRoute,
  protectedDashboardDatabasesIndexRoute: protectedDashboardDatabasesIndexRoute,
}

const protectedDashboardRouteWithChildren =
  protectedDashboardRoute._addFileChildren(protectedDashboardRouteChildren)

interface protectedRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRouteWithChildren
}

const protectedRouteChildren: protectedRouteChildren = {
  protectedDashboardRoute: protectedDashboardRouteWithChildren,
}

const protectedRouteWithChildren = protectedRoute._addFileChildren(
  protectedRouteChildren,
)

interface publicAuthTwoFactorRouteChildren {
  publicAuthTwoFactorSetupRoute: typeof publicAuthTwoFactorSetupRoute
}

const publicAuthTwoFactorRouteChildren: publicAuthTwoFactorRouteChildren = {
  publicAuthTwoFactorSetupRoute: publicAuthTwoFactorSetupRoute,
}

const publicAuthTwoFactorRouteWithChildren =
  publicAuthTwoFactorRoute._addFileChildren(publicAuthTwoFactorRouteChildren)

interface publicAuthRouteChildren {
  publicAuthSignInRoute: typeof publicAuthSignInRoute
  publicAuthSignUpRoute: typeof publicAuthSignUpRoute
  publicAuthTwoFactorRoute: typeof publicAuthTwoFactorRouteWithChildren
}

const publicAuthRouteChildren: publicAuthRouteChildren = {
  publicAuthSignInRoute: publicAuthSignInRoute,
  publicAuthSignUpRoute: publicAuthSignUpRoute,
  publicAuthTwoFactorRoute: publicAuthTwoFactorRouteWithChildren,
}

const publicAuthRouteWithChildren = publicAuthRoute._addFileChildren(
  publicAuthRouteChildren,
)

interface publicRouteChildren {
  publicAuthRoute: typeof publicAuthRouteWithChildren
}

const publicRouteChildren: publicRouteChildren = {
  publicAuthRoute: publicAuthRouteWithChildren,
}

const publicRouteWithChildren =
  publicRoute._addFileChildren(publicRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof protectedDashboardIndexRoute
  '/sign-in': typeof publicAuthSignInRoute
  '/sign-up': typeof publicAuthSignUpRoute
  '/two-factor': typeof publicAuthTwoFactorRouteWithChildren
  '/databases/$id': typeof protectedDashboardDatabasesIdRoute
  '/two-factor/setup': typeof publicAuthTwoFactorSetupRoute
  '/databases': typeof protectedDashboardDatabasesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof protectedDashboardIndexRoute
  '/sign-in': typeof publicAuthSignInRoute
  '/sign-up': typeof publicAuthSignUpRoute
  '/two-factor': typeof publicAuthTwoFactorRouteWithChildren
  '/databases/$id': typeof protectedDashboardDatabasesIdRoute
  '/two-factor/setup': typeof publicAuthTwoFactorSetupRoute
  '/databases': typeof protectedDashboardDatabasesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(protected)': typeof protectedRouteWithChildren
  '/(protected)/_dashboard': typeof protectedDashboardRouteWithChildren
  '/(public)': typeof publicRouteWithChildren
  '/(public)/_auth': typeof publicAuthRouteWithChildren
  '/(public)/_auth/sign-in': typeof publicAuthSignInRoute
  '/(public)/_auth/sign-up': typeof publicAuthSignUpRoute
  '/(public)/_auth/two-factor': typeof publicAuthTwoFactorRouteWithChildren
  '/(protected)/_dashboard/': typeof protectedDashboardIndexRoute
  '/(protected)/_dashboard/databases/$id': typeof protectedDashboardDatabasesIdRoute
  '/(public)/_auth/two-factor/setup': typeof publicAuthTwoFactorSetupRoute
  '/(protected)/_dashboard/databases/': typeof protectedDashboardDatabasesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor'
    | '/databases/$id'
    | '/two-factor/setup'
    | '/databases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/two-factor'
    | '/databases/$id'
    | '/two-factor/setup'
    | '/databases'
  id:
    | '__root__'
    | '/(protected)'
    | '/(protected)/_dashboard'
    | '/(public)'
    | '/(public)/_auth'
    | '/(public)/_auth/sign-in'
    | '/(public)/_auth/sign-up'
    | '/(public)/_auth/two-factor'
    | '/(protected)/_dashboard/'
    | '/(protected)/_dashboard/databases/$id'
    | '/(public)/_auth/two-factor/setup'
    | '/(protected)/_dashboard/databases/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  protectedRoute: typeof protectedRouteWithChildren
  publicRoute: typeof publicRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  protectedRoute: protectedRouteWithChildren,
  publicRoute: publicRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(protected)",
        "/(public)"
      ]
    },
    "/(protected)": {
      "filePath": "(protected)",
      "children": [
        "/(protected)/_dashboard"
      ]
    },
    "/(protected)/_dashboard": {
      "filePath": "(protected)/_dashboard.tsx",
      "parent": "/(protected)",
      "children": [
        "/(protected)/_dashboard/",
        "/(protected)/_dashboard/databases/$id",
        "/(protected)/_dashboard/databases/"
      ]
    },
    "/(public)": {
      "filePath": "(public)",
      "children": [
        "/(public)/_auth"
      ]
    },
    "/(public)/_auth": {
      "filePath": "(public)/_auth.tsx",
      "parent": "/(public)",
      "children": [
        "/(public)/_auth/sign-in",
        "/(public)/_auth/sign-up",
        "/(public)/_auth/two-factor"
      ]
    },
    "/(public)/_auth/sign-in": {
      "filePath": "(public)/_auth/sign-in.tsx",
      "parent": "/(public)/_auth"
    },
    "/(public)/_auth/sign-up": {
      "filePath": "(public)/_auth/sign-up.tsx",
      "parent": "/(public)/_auth"
    },
    "/(public)/_auth/two-factor": {
      "filePath": "(public)/_auth/two-factor.tsx",
      "parent": "/(public)/_auth",
      "children": [
        "/(public)/_auth/two-factor/setup"
      ]
    },
    "/(protected)/_dashboard/": {
      "filePath": "(protected)/_dashboard/index.tsx",
      "parent": "/(protected)/_dashboard"
    },
    "/(protected)/_dashboard/databases/$id": {
      "filePath": "(protected)/_dashboard/databases/$id.tsx",
      "parent": "/(protected)/_dashboard"
    },
    "/(public)/_auth/two-factor/setup": {
      "filePath": "(public)/_auth/two-factor.setup.tsx",
      "parent": "/(public)/_auth/two-factor"
    },
    "/(protected)/_dashboard/databases/": {
      "filePath": "(protected)/_dashboard/databases/index.tsx",
      "parent": "/(protected)/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
