import { ConnectionType } from '@tamery/shared/enums/connection-type'

export const COLUMN_TYPES: Record<ConnectionType, readonly string[]> = {
  [ConnectionType.ClickHouse]: [
    'UInt8',
    'UInt32',
    'UInt64',
    'Int32',
    'Int64',
    'Float32',
    'Float64',
    'Decimal(10, 2)',
    'String',
    'FixedString(36)',
    'UUID',
    'Bool',
    'Date',
    'DateTime',
    'DateTime64(3)',
  ],
  [ConnectionType.MSSQL]: [
    'int',
    'bigint',
    'smallint',
    'bit',
    'decimal(18, 2)',
    'float',
    'money',
    'varchar(255)',
    'nvarchar(255)',
    'nvarchar(max)',
    'uniqueidentifier',
    'date',
    'time',
    'datetime2',
    'varbinary(max)',
  ],
  [ConnectionType.MySQL]: [
    'int',
    'bigint',
    'smallint',
    'tinyint',
    'decimal(10, 2)',
    'float',
    'double',
    'boolean',
    'varchar(255)',
    'char(36)',
    'text',
    'date',
    'datetime',
    'timestamp',
    'json',
    'blob',
  ],
  [ConnectionType.Postgres]: [
    'integer',
    'bigint',
    'smallint',
    'numeric',
    'real',
    'double precision',
    'boolean',
    'text',
    'varchar(255)',
    'uuid',
    'date',
    'timestamp',
    'timestamptz',
    'jsonb',
    'bytea',
  ],
}
