import type { DialectSeedConfig } from '../registry'
import { PG_GENERATORS } from './generators'

export const pgSeedConfig = {
  generators: PG_GENERATORS,
  types: {
    bit: 'number.binary',
    box: 'postgres.box',
    bytea: 'postgres.bytea',
    cidr: 'internet.ip',
    circle: 'postgres.circle',
    datemultirange: 'postgres.datemultirange',
    daterange: 'postgres.daterange',
    geography: 'postgres.geometry',
    geometry: 'postgres.geometry',
    hstore: 'postgres.hstore',
    inet: 'internet.ip',
    int4multirange: 'postgres.intmultirange',
    int4range: 'postgres.intrange',
    int8multirange: 'postgres.intmultirange',
    int8range: 'postgres.intrange',
    interval: 'postgres.interval',
    line: 'postgres.line',
    lseg: 'postgres.lseg',
    ltree: 'postgres.ltree',
    macaddr: 'internet.mac',
    macaddr8: 'internet.mac',
    nummultirange: 'postgres.nummultirange',
    numrange: 'postgres.numrange',
    oid: 'number.int',
    path: 'postgres.path',
    point: 'postgres.point',
    polygon: 'postgres.polygon',
    tsmultirange: 'postgres.tsmultirange',
    tsquery: 'lorem.word',
    tsrange: 'postgres.tsrange',
    tstzmultirange: 'postgres.tsmultirange',
    tstzrange: 'postgres.tsrange',
    tsvector: 'lorem.sentence',
    varbit: 'number.binary',
    xml: 'lorem.sentence',
  },
} satisfies DialectSeedConfig
